### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by LogWell** [balbasty/torch-interpol#1]
I need to interpolate a SDF of say 128 x 128 x 128, as well as calculate normals (gradients). 
[Link](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.griddata.html) to `interpolate` in `scipy`.

Could you please provide an easy-to-use example?

**Comment by balbasty** [comment]
Hi,

The first thing is that the functions in this repo only work if the data to interpolate are defined on a regular grid (like [scipy.interpolate.interpn](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interpn.html), but not like [scipy.interpolate.griddata](scipy.interpolate.griddata)).

If that's what you're interested in, I've just added a [demo notebook](https://github.com/balbasty/torch-interpol/blob/main/examples/interpolate.ipynb). Let me know if that's the type of example you're looking for, or if you had something else in mind.

One last thing, I am not fully confident that the backward pass of `grid_grad` is correct. If you plan to backpropagate through it, maybe be careful, and please let me know if you get weird results.

Cheers
Yael

**Comment by LogWell** [comment]
Sorry, the links should be the following two [interpn](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interpn.html), [RegularGridInterpolator](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RegularGridInterpolator.html#scipy.interpolate.RegularGridInterpolator), and there are also some related issues: [14926](https://github.com/scipy/scipy/issues/14926) [16121](https://github.com/scipy/scipy/issues/16121).
I'll look at the relevant content first, and then ask you questions if I have any questions.
Thank you for your work.

**Comment by LogWell** [comment]
Hello, do you know how to pad texture like: https://www.youtube.com/watch?v=r9l8RfTvqyI , another question here: https://blender.stackexchange.com/questions/264966/inpainting-for-atlas-texture-map , I think it is related to interpolation, but I don't know how to implement it.
