### ISSUE TITLE
Issues when resampling 3D image using existing (affine) transform

### ISSUE THREAD

**Issue by pedrob37** [balbasty/torch-interpol#11]
Hello,

I've been looking for PyTorch-based methods to perform the resampling of 3D images, and this project seems very promising. However, I've found that there have been some inaccuracies when I carry out these resamplings, likely due to some error on my side.

My setup is as follows; I have a series of 3D Nifti images that I have affinely registered to a template space using a separate piece of software and have stored the corresponding affine transformation matrix for each. I use that same piece of software to resample the images to the template space using just the transform to ensure that they are correct. To try to replicate this process in Python using torch Interpol, I do the following:

```python
from interpol import grid_pull
from interpol.api import affine_grid
import nibabel as nib

def read_file(filename):
    img = nib.as_closest_canonical(nib.load(filename))
    data = img.get_fdata()
    aff = img.affine
    return data, aff


def save_img(image, affine, filename, header=None):
    nifti_img = nib.Nifti1Pair(image, affine, header)
    nib.save(nifti_img, filename)


# Load images
t1_vol, t1_aff = read_file(t1_image_path)
template_t1_vol, template_t1_aff = read_file(template_t1_image_path)

# Load transform
composed_array = np.load(composed_array_path)

center = np.eye(4)
center[:3, -1] = -np.array(template_t1_vol.shape) / 2
center = torch.as_tensor(center, dtype=torch.float)

full_affine = center.inverse() @ torch.as_tensor(composed_array, dtype=torch.float) @ center

# Build a dense field of sampling coordinates
grid = affine_grid(full_affine, template_t1_vol.shape)

# Resample
y1 = grid_pull(torch.as_tensor(t1_vol, dtype=torch.float), grid, bound='zero', interpolation=1)

save_img(y1.numpy(), template_t1_aff, f"reconstructed_interpol.nii.gz")
```

The saved images do not align with the template image.
Any help would be greatly appreciated on this matter; thank you.

**Comment by balbasty** [comment]
Hi,

It really depends how your third party software defines its affine transform. In your code, it seems that you assume that the transform operates at the center of both field of views, and maps voxels to voxels. Most registration software operate at the zero of the "RAS"/"world" space and map mm to mm. If it's your case, I would apply it like this:

```python
template_t1_aff = torch.as_tensor(template_t1_aff, dtype=float)
t1_aff =  torch.as_tensor(t1_aff, dtype=float)
composed_array =  torch.as_tensor(composed_array, dtype=float)
full_affine = t1_aff.inverse() @ composed_array @ template_t1_aff
```
It is also always ambiguous what direction is stored in the transform (i.e., a mapping from T1 space coordinates to Template space coordinates, or the inverse), so if it still does not look good, you could try
```python
full_affine = t1_aff.inverse() @ composed_array.inverse() @ template_t1_aff
```
Then , the rest of your code looks correct! Let me know how it goes.

Yael

**Comment by pedrob37** [comment]
Hi,

Thanks for getting back to me so quickly! I tried both approaches, even reversing the order of t1_aff and template_t1_aff, but everything resulted in an empty array. The code I outlined previously results in a closer but shifted (and therefore still unusable) resampled image. Is there any more information that I could provide that could help with solving this issue?

**Comment by balbasty** [comment]
OK, so it seems your transform does operate at the center of the FOV. Any chance you can point me to the code that estimated the transform?

Did you inverting the transform?  
```python
full_affine = center.inverse() @ composed_array.inverse() @ center
```
How big is the remaining shift? half a voxel, one voxel, more? If it's close to one voxel/half-voxel, maybe the center of the FOV should be computed as
```python
center = np.eye(4)
center[:3, -1] = -(np.array(template_t1_vol.shape) - 1)/ 2
```

I don't think the issue is in `interpol`, because I use it routinely to do exactly what you're trying to do, and it works as expected.

**Comment by pedrob37** [comment]
It must be something slightly off on my side, for sure. The shift is considerably more than one voxel:

![image](https://user-images.githubusercontent.com/33317198/235183616-4345b63f-6bde-4f8d-8588-3e6a26fb4935.png)

With the original image in its native space:

![image](https://user-images.githubusercontent.com/33317198/235183912-710624aa-3a1f-4ba8-9177-6a52c031374d.png)

I've tried inverting the transform and that results in a significantly worse alignment.

**Comment by balbasty** [comment]
It's a bit difficult to know how to use the transform without knowing how the registration code designed its transformation model. If you can get that information, that would be helpful.

Do the MRI and template have the same voxel size and shape? If they have different shapes, what if you use the center of each field of view independently, e.g.
```python
center_template = np.eye(4)
center_template[:3, -1] = -np.array(template_t1_vol.shape) / 2
center_mri = np.eye(4)
center_mri[:3, -1] = -np.array(t1_vol.shape) / 2

center_mri.inverse() @ composed_array @ center_template
```

**Comment by pedrob37** [comment]
Thanks for the feedback; I tried incorporating both centres into my code to no avail, but the images are still misaligned.

I used UniRes (sans the super-resolution component) to carry out the registration: https://github.com/brudfors/UniRes
I altered the code to be able to save the transformation matrix (This doesn't seem to be an option by default) and validated that the transformation was correct by using a different piece of registration software, NiftyReg, to resample the original image using the provided transform: https://github.com/KCL-BMEIS/niftyreg

**Comment by balbasty** [comment]
I think UniRes operate in world space, which corresponds to my initial snippet. It's weird that it didn't work then. Let's ask @brudfors for help!

**Comment by brudfors** [comment]
Hi Pedro!

Is it the atlas alignment that you are using from UniRes and then you save `mat_a`:

https://github.com/brudfors/UniRes/blob/master/unires/_core.py#L344

and now you want to resample the input image to the space of some atlas, and that atlas is aligned with the atlas used in the UniRes atlas registration (MNI)?

https://ndownloader.figshare.com/files/25595000/mb_avg218T1.nii.gz

**Comment by pedrob37** [comment]
Hey Mikael!

Exactly, I save mat_a from the coregistration step, and the mat_a from the atlas alignment step, and compose the two matrices to obtain the overall transformation.

That is indeed the same atlas I use, but for the resampling step I'm resampling to the image that UniRes outputs, which is in that space but has been cropped to a size of 192 x 256 x 256

**Comment by brudfors** [comment]
Hi Pedro,

The following code seems to work for me:

```py
import nibabel as nib
from interpol import grid_pull
from interpol.api import affine_grid
import torch

# Load data (x)
device = "cuda"
nii = nib.load(pth)
x = torch.as_tensor(nii.get_fdata(), device=device, dtype=torch.float)
mat_x = torch.as_tensor(nii.affine, device=device)

# UniRes
# data = [[x, mat_x]]
# s = settings()
# s.do_atlas_align = True
# ...some potential other settings...
# y_hat, mat_y, _ = preproc(data, sett=s)

# Compose transforms
mat = torch.linalg.solve(torch.linalg.solve(s.mat_atlas, mat_x), mat_y)
# Build affine grid
grid = affine_grid(mat, y_hat.shape).type(x.dtype)
# Resample
y = grid_pull(x[None, None, ...], grid[None, ...], bound='zero', extrapolate=False)[0, 0, ...]
```

Please pull the latest UniRes master branch as I have added a 'secret' return of the atlas transformation matrix. Also, for writing the image to disk, you want to use `mat_y` as its affine matrix.

Reg. co-registration, are you running UniRes with multiple input MRIs? Then you will have to modify the composition accordingly, depending on what image of the input scans you want to resample.

Btw, note that you can set `s.max_iter = 0` for UniRes to resample to the output space, instead of using its super-resolution algorithm.

**Comment by pedrob37** [comment]
Hi Mikael, Yael,

I've been on leave, so I apologise for the delay in getting back to you!

It turned out I was somehow incorrectly applying the transforms, and indeed the following works:

full_affine = t1_aff.inverse() @ composed_array @ template_t1_aff

The update to UniRes to save matrices will come in handy for further data processing, so it is very much appreciated!

**Comment by balbasty** [comment]
Glad you made it work!
