### ISSUE TITLE
Linear interpolation was not applied when splat a image

### ISSUE THREAD

**Issue by firstmover** [balbasty/torch-interpol#15]
Hi, 

Thank you for developing this tool. Recently, I have been working on problems involving slicing 2d images from 3d volume. I am hoping to use the function implemented in this repo for this operation. 

I have tried to use affine_grid and grid_pull function for slicing. And the outcome looked reasonable to me. However, I had some questions regarding the inverse operation of slicing -- splatting sliced images back to the original images. I did not get the expected results from your code. I was wondering if I might have missed something. 

Here is an example code on 2d data to reproduce my issue: 

```python 
import math
import urllib

import matplotlib.pyplot as plt
import numpy as np
import PIL
import torch

from interpol import grid_pull
from interpol.api import affine_grid


def main_slice_1d_from_2d_image():

    # we use image from internate
    image_url = (
        "https://upload.wikimedia.org/wikipedia/commons/b/b2/MRI_of_Human_Brain.jpg"
    )
    img = PIL.Image.open(urllib.request.urlopen(image_url))
    img = img.resize((64, 64))

    # gray scale numpy array
    img = np.array(img.convert("L"))
    img = torch.tensor(img)

    fig, ax = plt.subplots(1, 1)
    ax.imshow(img.numpy(), cmap="gray")
    fig.savefig("input_img.png")

    # align center to the middle of the image
    center = (img.shape[0] - 1) / 2
    S_center = torch.tensor(
        [
            [1, 0, -center],
            [0, 1, -center],
            [0, 0, 1],
        ],
        dtype=torch.float32,
    )

    # we rotate the image by theta degree
    theta = 30
    theta = math.radians(theta)
    S_rot = torch.tensor(
        [
            [math.cos(theta), -math.sin(theta), 0],
            [math.sin(theta), math.cos(theta), 0],
            [0, 0, 1],
        ],
        dtype=torch.float32,
    )

    # we slices a (thinkness, output_size) slice from
    # the image along the center
    thinkness = 10
    output_size = 64

    # from output image to centered image
    S_center_output = torch.tensor(
        [
            [1, 0, -(thinkness - 1) / 2],
            [0, 1, -(output_size - 1) / 2],
            [0, 0, 1],
        ],
        dtype=torch.float32,
    )

    int_interpo = 1

    # mapping from output image to input image
    full_affine = (S_rot @ S_center).inverse() @ S_center_output

    # build dense field of sampling coordinates
    grid = affine_grid(full_affine, [thinkness, output_size])
    output_img = grid_pull(img, grid, bound="mirror", interpolation=int_interpo)

    fig, ax = plt.subplots(1, 1)
    ax.imshow(output_img, cmap="gray")
    fig.savefig("output_img.png")

    # we put the transformed image back to the original space
    full_affine_inv = full_affine.inverse()
    grid = affine_grid(full_affine_inv, img.shape)
    output_img_splat = grid_pull(
        output_img, grid, bound="zero", interpolation=int_interpo
    )

    fig, ax = plt.subplots(1, 1)
    ax.imshow(output_img_splat, cmap="gray")
    fig.savefig("output_img_splat.png")

    # we also look at the occupancy
    output_img_ones_splat = grid_pull(
        torch.ones_like(output_img), grid, bound="zero", interpolation=int_interpo
    )

    fig, ax = plt.subplots(1, 1)
    im = ax.imshow(output_img_ones_splat, cmap="gray")
    fig.colorbar(im, ax=ax)
    fig.savefig("output_img_ones_splat.png")


if __name__ == "__main__":
    main_slice_1d_from_2d_image()
```

The outcome images are 
input_img:
![input_img](https://github.com/balbasty/torch-interpol/assets/22336818/15b32cae-93c5-4e54-8308-939e8988a277)

output_img (sliced image)
![output_img](https://github.com/balbasty/torch-interpol/assets/22336818/5af5e4e2-8a51-4f4a-b674-63ff9be892cd)

output_img put back to original image 
![output_img_splat](https://github.com/balbasty/torch-interpol/assets/22336818/d85fda2a-9e16-4070-a66b-74ccbb73c94e)

the occupancy of output_img on original input image 
![output_img_ones_splat](https://github.com/balbasty/torch-interpol/assets/22336818/5081c5c7-41fc-4cde-96b3-f85560cc3fa8)

The output image looked reasonable to me. But If we look at the splat image (that is, we put the sliced image back to the original image coordinate and see what are the part that is being sliced). I found that the boundaries of these images are not smooth. For example, in the occupancy image, the pixel values are either zero or one. I was expecting to get a value between zero and one around the boundary since we are using linear interpolation. Could you help me look at this issue?

**Comment by balbasty** [comment]
Hi!

There are two reasons:
1. Your input `img` does not have a floating data type. I am not sure I ever tested that case, but it seems I return a tensor wit the same data type as the input image, so bilinear weights are rounded to 0/1. You can use e.g. `img = torch.tensor(img).float()` to ensure that the image that is resliced has a floating point type.
2. By default `grid_pull` uses `extrapolate=False`, which means that coordinates that fall outside of the field of view of the input image are not computed. Outside of the field if view is determined as being before the center of the first voxel, or after the center of the last voxel, so no in-bounds voxels make use the extrapolated zeros. If you set `extrapolate=True`, you'll see smooth edges

![output_img_splat](https://github.com/balbasty/torch-interpol/assets/7803834/9b8492f8-5767-45a6-a444-391fbba8dbff)
![output_img_ones_splat](https://github.com/balbasty/torch-interpol/assets/7803834/164e0be1-9894-4f95-93e1-9d65abead901)

Note also that you're not really splatting here, but re-slicing the sliced image. The `grid_push` utility implements an alternative way of splatting (defined as the operation adjoint to `grid_pull`), which results in someting like this (see code below for what these images are):

![output_img_ones_push](https://github.com/balbasty/torch-interpol/assets/7803834/16b6f95b-dcf9-4d6f-8d8a-c9678590827d)

Here's the code with the extra bits (sorry I extracted it out of the function and ran it in a notebook)
```python
import math
import urllib

import matplotlib.pyplot as plt
import numpy as np
import PIL
import torch

from interpol import grid_pull, grid_push, grid_count
from interpol.api import affine_grid

# we use image from internate
image_url = (
    "https://upload.wikimedia.org/wikipedia/commons/b/b2/MRI_of_Human_Brain.jpg"
)
img = PIL.Image.open(urllib.request.urlopen(image_url))
img = img.resize((64, 64))

# gray scale numpy array
img = np.array(img.convert("L"))
img = torch.tensor(img).float()

fig, ax = plt.subplots(1, 1)
ax.imshow(img.numpy(), cmap="gray")
fig.savefig("input_img.png")

# align center to the middle of the image
center = (img.shape[0] - 1) / 2
S_center = torch.tensor(
    [
        [1, 0, -center],
        [0, 1, -center],
        [0, 0, 1],
    ],
    dtype=torch.float32,
)

# we rotate the image by theta degree
theta = 30
theta = math.radians(theta)
S_rot = torch.tensor(
    [
        [math.cos(theta), -math.sin(theta), 0],
        [math.sin(theta), math.cos(theta), 0],
        [0, 0, 1],
    ],
    dtype=torch.float32,
)

# we slices a (thinkness, output_size) slice from
# the image along the center
thinkness = 10
output_size = 64

# from output image to centered image
S_center_output = torch.tensor(
    [
        [1, 0, -(thinkness - 1) / 2],
        [0, 1, -(output_size - 1) / 2],
        [0, 0, 1],
    ],
    dtype=torch.float32,
)

int_interpo = 1

# mapping from output image to input image
full_affine = (S_rot @ S_center).inverse() @ S_center_output

# build dense field of sampling coordinates
grid = affine_grid(full_affine, [thinkness, output_size])
output_img = grid_pull(img, grid, bound="mirror", interpolation=int_interpo)

fig, ax = plt.subplots(1, 1)
ax.imshow(output_img, cmap="gray")
fig.savefig("/tmp/output_img.png")

# we put the transformed image back to the original space
full_affine_inv = full_affine.inverse()
igrid = affine_grid(full_affine_inv, img.shape)
output_img_splat = grid_pull(
    output_img, igrid, bound="zero", interpolation=int_interpo,
    extrapolate=True,
)

fig, ax = plt.subplots(1, 1)
ax.imshow(output_img_splat, cmap="gray")
fig.savefig("/tmp/output_img_splat.png")

# we also look at the occupancy
output_img_ones_splat = grid_pull(
    torch.ones_like(output_img), igrid, bound="zero", interpolation=int_interpo,
    extrapolate=True,
)

fig, ax = plt.subplots(1, 1)
im = ax.imshow(output_img_ones_splat, cmap="gray")
fig.colorbar(im, ax=ax)
fig.savefig("/tmp/output_img_ones_splat.png")

# splat with grid_push
output_img_push = grid_push(
    output_img, grid, img.shape, bound="mirror", interpolation=int_interpo,
)
output_img_count = grid_count(
    grid, img.shape, bound="mirror", interpolation=int_interpo,
)

fig, ax = plt.subplots(1, 3)
im = ax[0].imshow(output_img_push, cmap="gray")
im = ax[1].imshow(output_img_count, cmap="gray")
im = ax[2].imshow(output_img_push / output_img_count.clamp_min(1e-8), cmap="gray")
fig.savefig("/tmp/output_img_ones_push.png")

```

**Comment by firstmover** [comment]
Thank you for the detailed response! It makes a lot of sense. I will spend more time playing with the code. And I will let you know if I have more questions.
