### ISSUE TITLE
Boundary processing of depth maps

### ISSUE THREAD

**Issue by LogWell** [balbasty/torch-interpol#8]
For depth maps, the invalid pixels are usually set to 0. How to handle the boundary of such data during interpolation?
![image](https://user-images.githubusercontent.com/34391447/199065395-90c7f4da-fc0a-4b45-a485-90f925e75cf2.png)

ps: The primary in rendering is a triangle, so the barycentric interpolation of the triangle and bilinear interpolation may be involved here: mesh formed from image
![image](https://user-images.githubusercontent.com/34391447/199066128-8e8cbd4d-bdbe-4c1e-b132-d0c30e022891.png)

**Comment by balbasty** [comment]
Hi,

If you set `extrapolate = True`, the boundary condition specified using the `bound` keyword will be used to fill out-of-bound values. Would that help?

**Edit:** Maybe I misunderstood your question. Do you mean that you want some values (e.g. 0) to not be used in the interpolation? This code does not handle such cases. You could try to fill these missing values using e.g. the nearest valid value? This would be equivalent to using the boundary condition "nearest" for out-of-bound data.

Cheers
Yael
